// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

// Credentials defines model for Credentials.
type Credentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Error defines model for Error.
type Error struct {
	Code     int     `json:"code"`
	Internal *string `json:"internal,omitempty"`
	Message  string  `json:"message"`
	Subcode  int     `json:"subcode"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// ScoreboardPreferences defines model for ScoreboardPreferences.
type ScoreboardPreferences struct {
	AwayBg        *string `json:"awayBg,omitempty"`
	AwayFg        *string `json:"awayFg,omitempty"`
	AwayName      *string `json:"awayName,omitempty"`
	Bg            *string `json:"bg,omitempty"`
	Fg            *string `json:"fg,omitempty"`
	HomeBg        *string `json:"homeBg,omitempty"`
	HomeFg        *string `json:"homeFg,omitempty"`
	HomeName      *string `json:"homeName,omitempty"`
	PointsBg      *string `json:"pointsBg,omitempty"`
	PointsFg      *string `json:"pointsFg,omitempty"`
	SetBg         *string `json:"setBg,omitempty"`
	SetFg         *string `json:"setFg,omitempty"`
	SetLabel      *string `json:"setLabel,omitempty"`
	TimeoutsBg    *string `json:"timeoutsBg,omitempty"`
	TimeoutsLabel *string `json:"timeoutsLabel,omitempty"`
}

// ScoreboardStatus defines model for ScoreboardStatus.
type ScoreboardStatus struct {
	AwayPoints   *int `json:"awayPoints,omitempty"`
	AwaySets     *int `json:"awaySets,omitempty"`
	AwayTimeouts *int `json:"awayTimeouts,omitempty"`
	HomePoints   *int `json:"homePoints,omitempty"`
	HomeSets     *int `json:"homeSets,omitempty"`
	HomeTimeouts *int `json:"homeTimeouts,omitempty"`
}

// Session defines model for Session.
type Session struct {
	ExpiresIn *int   `json:"expiresIn,omitempty"`
	Token     string `json:"token"`
	Username  string `json:"username"`
}

// sessionPostJSONBody defines parameters for SessionPost.
type sessionPostJSONBody Credentials

// SessionPostRequestBody defines body for SessionPost for application/json ContentType.
type SessionPostJSONRequestBody sessionPostJSONBody
